// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA5PApJrJOqMN-toLSZXOsZGhGsSYBsUc',
    appId: '1:294768462523:web:2e85354253c08707f7b79e',
    messagingSenderId: '294768462523',
    projectId: 'barber-app-d342a',
    authDomain: 'barber-app-d342a.firebaseapp.com',
    storageBucket: 'barber-app-d342a.firebasestorage.app',
    measurementId: 'G-M468KF89HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjz39I37hd2OIpbh8qX55hDD_KTVmi0X0',
    appId: '1:294768462523:android:5043998cdbdbaf0ff7b79e',
    messagingSenderId: '294768462523',
    projectId: 'barber-app-d342a',
    storageBucket: 'barber-app-d342a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeqzdyl112JBdWeaeImFp3wx2p2UyrYcc',
    appId: '1:294768462523:ios:cd3d075bf45912def7b79e',
    messagingSenderId: '294768462523',
    projectId: 'barber-app-d342a',
    storageBucket: 'barber-app-d342a.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeqzdyl112JBdWeaeImFp3wx2p2UyrYcc',
    appId: '1:294768462523:ios:cd3d075bf45912def7b79e',
    messagingSenderId: '294768462523',
    projectId: 'barber-app-d342a',
    storageBucket: 'barber-app-d342a.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA5PApJrJOqMN-toLSZXOsZGhGsSYBsUc',
    appId: '1:294768462523:web:f414125bc97f456af7b79e',
    messagingSenderId: '294768462523',
    projectId: 'barber-app-d342a',
    authDomain: 'barber-app-d342a.firebaseapp.com',
    storageBucket: 'barber-app-d342a.firebasestorage.app',
    measurementId: 'G-B5Y7PXGCBN',
  );

}